// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSP8aoBNm7GxW25ab7imeR4cKbkC3mXkA',
    appId: '1:817395195895:web:5ef19da450bdfe99dd18f2',
    messagingSenderId: '817395195895',
    projectId: 'ns-customer-info-share-84343',
    authDomain: 'ns-customer-info-share-84343.firebaseapp.com',
    databaseURL: 'https://ns-customer-info-share-84343-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ns-customer-info-share-84343.appspot.com',
    measurementId: 'G-45KBJ4YFWB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6sHreZUQd_HuMC-hth6wbswvYaVDA4eM',
    appId: '1:817395195895:android:0b5f00e55c57e8c1dd18f2',
    messagingSenderId: '817395195895',
    projectId: 'ns-customer-info-share-84343',
    databaseURL: 'https://ns-customer-info-share-84343-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ns-customer-info-share-84343.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZQVlcNA4Tjwp41fkDf4I5f91Hkg7DiCc',
    appId: '1:817395195895:ios:323f6f93daa0c4d2dd18f2',
    messagingSenderId: '817395195895',
    projectId: 'ns-customer-info-share-84343',
    databaseURL: 'https://ns-customer-info-share-84343-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ns-customer-info-share-84343.appspot.com',
    iosBundleId: 'com.example.customerInfoShare',
  );
}
